# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cb61cb903682902dc7d7a5b759374d23fcfad17ff6133e13b92e62a29c848b15e39740cf632ab5296424582bf1f8435a02f166e7d305a84e7eb9cbaca1c11d5

test:
  secret_key_base: 68533ff18df1abe8a7eb48dcca5bf0725ce3f0147f7ba60cd768a4bcad898f1d52471909ca5aa507a37100d262a2f498b83ca360dc1e9a95b678737d9d1d60a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
