# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73ecb36bd33f95411885e988ef86b597f70fca5cd20c47421402c8333f5c847549d1e4b0a09cff233c05002b35948dc86fad9fded936bcfd0d89fddbbb93369f

test:
  secret_key_base: 5c6e883ab91058e08426d21f045c6360c98a218a5d451f8aad91c9e04d6a9e8f4f4c3a72839c2e422ab183db6659a7a3fbc08fe16b8ecafe8a112f8f000c4238

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
